{% set name = "acpype" %}
{% set version = "2020.05.27.16.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/alanwilter/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1ffb8dbba415c7a1ed83f6d3af26356da043b2636d3a851c983fab51e2987efc
build:
  number: 0
  script:
    - mv recipe/setup_conda.py setup.py
    - {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - acpype=scripts.acpype:init_main
requirements:
  host:
    - python >=3
    - pip
  run:
    - openbabel
    - python >=3
    - ambertools
test:
  commands:
    - acpype -h
about:
  home: https://github.com/alanwilter/acpype
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Generates topologies for chemical compounds
  description: |
    A tool based in Python to use Antechamber to generate topologies 
    for chemical compounds and to interface with other python 
    applications like CCPN or ARIA.

  doc_url: https://github.com/alanwilter/acpype
  dev_url: https://github.com/alanwilter/acpype

extra:
  recipe-maintainers:
    - simonbray
