{% set name = "acpype" %}
{% set version = "2023.10.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/alanwilter/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 51dc45383c8efa0504075286226039c6baba9039311093b01e6d1b3ad88b1f44
build:
  number: 1
  script:
    - mv recipe/setup_conda.py setup.py
    - {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - acpype=acpype.cli:init_main
requirements:
  host:
    - python {{ python_min }}
    - poetry
    - pip
  run:
    - openbabel
    - python >={{ python_min }}
    - ambertools
    - parmed
    - numpy
    - scipy
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  commands:
    - acpype -h
about:
  home: https://github.com/alanwilter/acpype
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Generates topologies for chemical compounds
  description: |
    A tool based in Python to use Antechamber to generate topologies 
    for chemical compounds and to interface with other python 
    applications like CCPN or ARIA.

  doc_url: https://github.com/alanwilter/acpype
  dev_url: https://github.com/alanwilter/acpype

extra:
  recipe-maintainers:
    - alanwilter
    - lkagami
    - simonbray
