{% set name = "acpype" %}
{% set version = "2019.10.05.12.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
    url: https://github.com/alanwilter/{{ name }}/archive/fbe19e5ab1733b22bf15a6ccece615f86c420a74.tar.gz
    sha256: 19bc474dac9351833f26ae5e6d33c4f7ca178ebe2b52d30ca54135d0d423a469
build:
    number: 1
    script:
        - mv recipe/setup_conda.py setup.py
        - "{{ PYTHON }} -m pip install . -vv"
    noarch: python
    entry_points: 
        - acpype=anaconda.acpype:init_main
requirements:
    host:
        - python >=3
        - pip
    run:
        - openbabel
        - python >=3
        - ambertools
test:
    commands:
        - acpype -h
about:
    home: https://github.com/alanwilter/acpype
    license: GPL-3.0
    license_family: GPL
    license_file: LICENSE
    summary: 'Generates topologies for chemical compounds'
    description: |
      A tool based in Python to use Antechamber to generate topologies 
      for chemical compounds and to interface with other python 
      applications like CCPN or ARIA.
      
    doc_url: https://github.com/alanwilter/acpype
    dev_url: https://github.com/alanwilter/acpype

extra:
  recipe-maintainers:
    - simonbray
